version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: admin-postgres
    environment:
      POSTGRES_DB: admin_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - admin-network

  redis:
    image: redis:7-alpine
    container_name: admin-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - admin-network

volumes:
  postgres_data:
  redis_data:

networks:
  admin-network:
    driver: bridge